const actionTypes = {
    "CAN_CASTLE" : "CAN_CASTLE",
    "STALEMATE" : "STALEMATE", 
    "NEW_GAME" : "NEW_GAME",
    "CLEAR_CANDIDATE_MOVES" : "CLEAR_CANDIDATE_MOVES",
    "GENERATE_CANDIDATE_MOVES" : "GENERATE_CANDIDATE_MOVES",
    "NEW_MOVE" : "NEW_MOVE",
    "PROMOTION_CLOSE" : "PROMOTION_CLOSE",
    "PROMOTION_OPEN" : "PROMOTION_OPEN",
    "SET_PROMOTION_STATUS" : "SET_PROMOTION_STATUS", // Track promotion status for all players
    "INSUFFICIENT_MATERIAL" : "INSUFFICIENT_MATERIAL",
    "WIN" : "WIN",

}
 
export default actionTypes